## Day-7 session - 26th February 2022 on python

1. Numpy

    a. shape, ndim, reshape, default array
    
    b. Create an array with existing data
    
    c. Array from numerical ranges
    
    d. Slicing
    
    e. Integer Indexing
    
    f. nan (null values concept)`

### Numpy and Pandas

Numpy(Numerical python) - it is for arrays, numeric calculations

Pandas is for a dataframes(table), calculation, performance is slow

### Numpy

In [2]:
import numpy as np

In [12]:
array1 = np.array([1, 2, 3, 4, 5])

In [4]:
array1

array([1, 2, 3, 4, 5])

In [5]:
type(array1)

numpy.ndarray

In [7]:
array1.shape

(5,)

In [13]:
array1.ndim

1

In [14]:
array2 = np.array([[1, 2, 3, 4, 5], [11, 22, 33, 44, 55]])

In [16]:
array2.shape

(2, 5)

In [17]:
array2

array([[ 1,  2,  3,  4,  5],
       [11, 22, 33, 44, 55]])

In [18]:
array3 = np.array([1,2,3], [4,5,6,7]) # arrays sequence should be in order

TypeError: Field elements must be 2- or 3-tuples, got '4'

In [24]:
array4 = np.array([[1, 'sant', 50.9], [2, 'imran', 89.87], [3, 'Raj', 100.0]])

In [25]:
array4.shape

(3, 3)

In [26]:
array4

array([['1', 'sant', '50.9'],
       ['2', 'imran', '89.87'],
       ['3', 'Raj', '100.0']], dtype='<U32')

In [27]:
array5 = np.array([[1, 2, 3, 4, 5], [11, 22, 33, 44, 55]], dtype = float)

In [28]:
array5

array([[ 1.,  2.,  3.,  4.,  5.],
       [11., 22., 33., 44., 55.]])

In [29]:
array5.shape

(2, 5)

In [41]:
array_reshape = array5.reshape(5,2)

In [42]:
array_reshape

array([[ 1.,  2.],
       [ 3.,  4.],
       [ 5., 11.],
       [22., 33.],
       [44., 55.]])

In [43]:
array_reshape = array5.reshape(10,1)

In [44]:
array_reshape

array([[ 1.],
       [ 2.],
       [ 3.],
       [ 4.],
       [ 5.],
       [11.],
       [22.],
       [33.],
       [44.],
       [55.]])

In [45]:
array_reshape = array5.reshape(1,10)

In [46]:
array_reshape

array([[ 1.,  2.,  3.,  4.,  5., 11., 22., 33., 44., 55.]])

In [ ]:
array_zero = np.zeros(8)

In [50]:
array5.shape?

In [51]:
array6 = np.array([[[[1,2,3,4,5],[4,5,6,7,8],[1.2,3.4,5.6,7.8,9.1],[4,4,4,4,5]]]])


In [52]:
array6

array([[[[1. , 2. , 3. , 4. , 5. ],
         [4. , 5. , 6. , 7. , 8. ],
         [1.2, 3.4, 5.6, 7.8, 9.1],
         [4. , 4. , 4. , 4. , 5. ]]]])

In [61]:
array6.shape   ## No use with this example having multiple dimensions in the same

(1, 1, 4, 5)

In [55]:
array7 = np.array([[1,2,3,4,5],[4,5,6,7,8],[1.2,3.4,5.6,7.8,9.1],[4,4,4,4,5]])


In [56]:
array7.shape

(4, 5)

In [63]:
iter?

In [66]:
array7 = np.array([[[1,2,3,4,5],[4,5,6,7,8]],[[1,3,5,7,9],[4,4,4,4,5]]])

In [122]:
len(array7)

2

In [67]:
array7.shape

(2, 2, 5)

In [68]:
array_zero = np.zeros(8)

In [69]:
array_zero

array([0., 0., 0., 0., 0., 0., 0., 0.])

In [73]:
array_ones = np.ones([3,3], dtype=int)

In [74]:
array_ones

array([[1, 1, 1],
       [1, 1, 1],
       [1, 1, 1]])

### Creating an array with existing data

In [81]:
x1 = ([3, 5], [5,4], [6,7])

In [256]:
n1 = ([[3, 5], [5,4], [6,7]], dtype = float)

SyntaxError: invalid syntax (Temp/ipykernel_16128/1213016252.py, line 1)

In [82]:
a1 = np.asarray(x1, dtype=float)  ## asarray() is a function

In [83]:
type(x1)

tuple

In [84]:
x1

([3, 5], [5, 4], [6, 7])

In [85]:
a1

array([[3., 5.],
       [5., 4.],
       [6., 7.]])

### Array from Numerical ranges

In [92]:
a1 = np.arange(0,20,3)

In [93]:
a1

array([ 0,  3,  6,  9, 12, 15, 18])

In [96]:
a1 = np.linspace(10,20,3)

In [97]:
a1

array([10., 15., 20.])

In [98]:
a1 = np.linspace(10,20,6)

In [99]:
a1

array([10., 12., 14., 16., 18., 20.])

In [100]:
a1 = np.linspace(10,20,5)

In [101]:
a1

array([10. , 12.5, 15. , 17.5, 20. ])

### Slicing 

In [107]:
list1 = np.arange(10)

#list1

In [108]:
array1 = slice(2,9,2)


In [110]:
list1[array1]

array([2, 4, 6, 8])

In [112]:
list2 = list1[array1]

In [113]:
list2

array([2, 4, 6, 8])

In [111]:
list1

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [114]:
array2 = slice(2,9)
list1[array2]

array([2, 3, 4, 5, 6, 7, 8])

In [116]:
list1 = np.arange(10)
array1 = list1[2: 9: 2]
list1[array1]

array([2, 4, 6, 8])

In [119]:
array1 = list1[2: 9]

In [120]:
array1

array([2, 3, 4, 5, 6, 7, 8])

In [121]:
len(array1)

7

In [123]:
array1.ndim

1

In [148]:
array7 = np.array([[[1,2,3,4,5],[4,5,6,7,8]],[[1,3,5,7,9],[4,4,4,4,5]]])

In [143]:
len(array7[1][1])

5

In [144]:
array7.shape

(2, 2, 5)

In [149]:
array7.ndim

3

In [134]:
len(array7[0][1])

5

In [153]:
array7 = np.array([[1,2,3,4,5],[4,5,6,7,8],[1,3,5,7,9],[4,4,4,4,5]])

In [154]:
len(array7)

4

In [155]:
len(array7[2])

5

In [146]:
array7.shape

(4, 5)

In [147]:
array7.ndim

2

In [156]:
array7= np.array([[[1,3,4,5],[3,4,5,6],[3,4,5,6]],[[5,4,5,6],[3,4,5,6],[3,4,5,6]],[[5,4,5,6],[3,4,5,6],[3,4,5,6]]])


In [157]:
array7

array([[[1, 3, 4, 5],
        [3, 4, 5, 6],
        [3, 4, 5, 6]],

       [[5, 4, 5, 6],
        [3, 4, 5, 6],
        [3, 4, 5, 6]],

       [[5, 4, 5, 6],
        [3, 4, 5, 6],
        [3, 4, 5, 6]]])

In [158]:
array7.ndim

3

In [159]:
array7.shape

(3, 3, 4)

### Integer indexing

In [161]:
a = np.array([[1,2],[3,4],[5,6]])
b = a[[0,1,2],[0,1,0]]

In [163]:
a

array([[1, 2],
       [3, 4],
       [5, 6]])

In [164]:
b

array([1, 4, 5])

In [167]:
a[1][0]

3

In [183]:
a1 = np.array([[1,2,3,4],[11,22,33,44],[111,222,333,444],[1111,2222,3333,4444]])

In [188]:
b1 = a1[1:,1:]

In [189]:
b1

array([[  22,   33,   44],
       [ 222,  333,  444],
       [2222, 3333, 4444]])

In [190]:
a1[1:][1:]   # don't use it

array([[ 111,  222,  333,  444],
       [1111, 2222, 3333, 4444]])

In [191]:
a1[1:4,1:3]

array([[  22,   33],
       [ 222,  333],
       [2222, 3333]])

In [192]:
b = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9], [10, 11, 12]])

In [195]:
b

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [193]:
b1 = b[1:4, [1,2]]

In [194]:
b1

array([[ 5,  6],
       [ 8,  9],
       [11, 12]])

In [196]:
b1 = b[:4, :3]

In [197]:
b1

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [198]:
a1 = np.array([[1,2,3,4],[11,22,33,44],[111,222,333,444],[1111,2222,3333,4444]])

In [199]:
a1

array([[   1,    2,    3,    4],
       [  11,   22,   33,   44],
       [ 111,  222,  333,  444],
       [1111, 2222, 3333, 4444]])

In [200]:
x = a1[1:5, [1,2,3]]

In [201]:
x

array([[  22,   33,   44],
       [ 222,  333,  444],
       [2222, 3333, 4444]])

In [202]:
a1[0:, [1,2,3]]

array([[   2,    3,    4],
       [  22,   33,   44],
       [ 222,  333,  444],
       [2222, 3333, 4444]])

In [206]:
a1[0:, [1,2]]

array([[   2,    3],
       [  22,   33],
       [ 222,  333],
       [2222, 3333]])

In [213]:
a1[1:,[1,2]]

array([[  22,   33],
       [ 222,  333],
       [2222, 3333]])

In [220]:
a1[[1,2,3],1:3]

array([[  22,   33],
       [ 222,  333],
       [2222, 3333]])

In [221]:
a1

array([[   1,    2,    3,    4],
       [  11,   22,   33,   44],
       [ 111,  222,  333,  444],
       [1111, 2222, 3333, 4444]])

In [223]:
a1[a1<4]

array([1, 2, 3])

In [224]:
a1[a1>=4]

array([   4,   11,   22,   33,   44,  111,  222,  333,  444, 1111, 2222,
       3333, 4444])

### nan example - null values

In [231]:
a2 = np.array([1, 5, np.nan, 8, np.nan, 52, 65, np.nan])   # nan means a null value

In [228]:
a2

array([ 1.,  5., nan,  8., nan, 52., 65., nan])

In [229]:
a2[np.isnan(a2)]

array([nan, nan, nan])

In [230]:
a2[~np.isnan(a2)]

array([ 1.,  5.,  8., 52., 65.])

In [232]:
a1

array([[   1,    2,    3,    4],
       [  11,   22,   33,   44],
       [ 111,  222,  333,  444],
       [1111, 2222, 3333, 4444]])

In [252]:
a1[np.isnan(a1)]

array([], dtype=int32)

In [233]:
a1[2,3]

444

In [251]:
for a in a1:
    if a == 222:
        print(a)

ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()