## Day-8 session - 27th February 2022 on python

1. Numpy

    a. Broadcasting an arry
    
    b. flatten, 
    
    c. Concatenate, stack, axis, vstack, hstack, delete, insert, append, unique, add, multiply, subtraction, division functions
    
    d. median, mean, std functions
    

2. Pandas (Using Pandas we can do operations on dataframe) - dataframe is same as table(rows and columns)


### Broadcasting an array

In [5]:
import numpy as np

In [7]:
x = np.array([1,2,3])
y = np.array([11,12,13]) 

In [8]:
z=x*y
z

array([11, 24, 39])

In [9]:
x = np.array([1,2,3])
y = 5                        # here y value is the scalar value in the array multiplication

In [10]:
z=x*y
z

array([ 5, 10, 15])

In [14]:
np.add(x,y)

array([6, 7, 8])

In [19]:
x = np.array([[1,2,3],[3,4,5]])
y = np.array([[11,12,13],[13,14,15]])

z = x*y
z

array([[11, 24, 39],
       [39, 56, 75]])

In [20]:
x = np.array([[1,2,3],[3,4,5]])
y = 3

z = x*y
z

array([[ 3,  6,  9],
       [ 9, 12, 15]])

In [60]:
x = np.array([1,2,3])
y = np.array([[11,12,13],[13,14,15]])

z = x*y
z

array([[11, 24, 39],
       [13, 28, 45]])

In [61]:
len(x)

3

In [64]:
len(y)

2

In [76]:
y_row = len(y)
y_col = len(y[0])
for i in range(y_row):
    for j in range(y_col):
        if y[i][j] == 13:
            a = i
            print(a)
            print(y[i][j])
print(a)

for a in range(y_row):
    print(y[a])

0
13
1
13
1
[11 12 13]
[13 14 15]


In [74]:
for a in range(y_row):
    print(y[a])

[11 12 13]
[13 14 15]


In [31]:
array_reshape1 = y.reshape(1,9)

In [32]:
array_reshape1

array([[11, 12, 13, 13, 14, 15, 22, 33, 11]])

In [36]:
x = np.array([[11,12,13],[13,14,15],[22,33,11]])
y = np.array([1,2,3])

z = x*y
z

array([[11, 24, 39],
       [13, 28, 45],
       [22, 66, 33]])

In [38]:
z.T    ## Where we will use it

array([[11, 13, 22],
       [24, 28, 66],
       [39, 45, 33]])

In [40]:
array1 = np.arange(8).reshape(4,2)

In [41]:
array1

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7]])

In [42]:
array1.flatten()

array([0, 1, 2, 3, 4, 5, 6, 7])

In [53]:
x = np.array([[1,2,3],[3,4,5]])
y = np.array([[11,12,13],[13,14,15],[33,44,55],[88,99,1]])

np.concatenate((x,y))


array([[ 1,  2,  3],
       [ 3,  4,  5],
       [11, 12, 13],
       [13, 14, 15],
       [33, 44, 55],
       [88, 99,  1]])

In [47]:
np.stack((x,y))

array([[[ 1,  2,  3],
        [ 3,  4,  5]],

       [[11, 12, 13],
        [13, 14, 15]]])

In [77]:
arrays = [np.random.randn(2, 2) for _ in range(2)]

In [78]:
arrays

[array([[-0.18630378, -0.07203027],
        [-1.62598242, -0.43799735]]),
 array([[ 2.01400255,  0.11252889],
        [-1.03296749, -0.35481581]])]

In [79]:
np.stack(arrays, axis = 0)

array([[[-0.18630378, -0.07203027],
        [-1.62598242, -0.43799735]],

       [[ 2.01400255,  0.11252889],
        [-1.03296749, -0.35481581]]])

In [95]:
x = np.array([[1,2],[3,4],[5,6]])
y = np.array([[11,12],[14,15],[16,17]])

np.concatenate((x,y))

array([[ 1,  2],
       [ 3,  4],
       [ 5,  6],
       [11, 12],
       [14, 15],
       [16, 17]])

In [96]:
np.stack((x,y), axis=0)   ## axis=0 is row wise operation

array([[[ 1,  2],
        [ 3,  4],
        [ 5,  6]],

       [[11, 12],
        [14, 15],
        [16, 17]]])

In [97]:
np.stack((x,y), axis=1)   ## axis=1 is column wise operation

array([[[ 1,  2],
        [11, 12]],

       [[ 3,  4],
        [14, 15]],

       [[ 5,  6],
        [16, 17]]])

In [100]:
print(x)
print(y)

[[1 2]
 [3 4]
 [5 6]]
[[11 12]
 [14 15]
 [16 17]]


In [98]:
np.vstack((x,y))        ## compare with axis = 0

array([[ 1,  2],
       [ 3,  4],
       [ 5,  6],
       [11, 12],
       [14, 15],
       [16, 17]])

In [99]:
np.hstack((x,y))        ## compare with axis = 1

array([[ 1,  2, 11, 12],
       [ 3,  4, 14, 15],
       [ 5,  6, 16, 17]])

In [109]:
a = np.arange(6)
np.split(a,2)

[array([0, 1, 2]), array([3, 4, 5])]

In [108]:
a = np.arange(15)
np.split(a,2)

ValueError: array split does not result in an equal division

In [116]:
a = np.array([[1,2,3],[2,3,4]])

In [117]:
b = np.array([[10,20,30],[20,30,40]])


In [118]:
np.append(a,b, axis=0)

array([[ 1,  2,  3],
       [ 2,  3,  4],
       [10, 20, 30],
       [20, 30, 40]])

In [120]:
np.append(a,[[10, 20, 30], [20,30,50]], axis=0)

array([[ 1,  2,  3],
       [ 2,  3,  4],
       [10, 20, 30],
       [20, 30, 50]])

In [122]:
np.append(a,[[10, 20, 30]], axis=1)

ValueError: all the input array dimensions for the concatenation axis must match exactly, but along dimension 0, the array at index 0 has size 2 and the array at index 1 has size 1

In [124]:
a

array([[1, 2, 3],
       [2, 3, 4]])

In [123]:
np.append(a,[[10, 20, 30],[20,30,40]], axis=1)

array([[ 1,  2,  3, 10, 20, 30],
       [ 2,  3,  4, 20, 30, 40]])

In [125]:
np.append(a,[[10, 20, 30],[20,30,40]], axis=0)

array([[ 1,  2,  3],
       [ 2,  3,  4],
       [10, 20, 30],
       [20, 30, 40]])

In [127]:
a

array([[1, 2, 3],
       [2, 3, 4]])

In [142]:
x=np.insert(a,1,[11,33,66],axis=0)

In [139]:
np.insert(a,1,66,axis=1)

array([[ 1, 66,  2,  3],
       [ 2, 66,  3,  4]])

In [143]:
x

array([[ 1,  2,  3],
       [11, 33, 66],
       [ 2,  3,  4]])

In [147]:
y = np.delete(x,1,axis=1)

In [148]:
y

array([[ 1,  3],
       [11, 66],
       [ 2,  4]])

In [150]:
a

array([[1, 2, 3],
       [2, 3, 4]])

In [151]:
x

array([[ 1,  2,  3],
       [11, 33, 66],
       [ 2,  3,  4]])

In [152]:
uniq = np.array([1,2,43,4,5,6,7,7,8,8])
np.unique(uniq)

array([ 1,  2,  4,  5,  6,  7,  8, 43])

In [162]:
a = np.array([[1,2],[3,4]])
b = np.array([[11,12],[22,11]]) 

print('addition of two matrices')
print(np.add(a,b))
print('\n')
print('subtraction of two matrices')
print(np.subtract(a,b))
print('\n')
print('multiply of two matrices')
print(np.multiply(a,b))
print('\n')
print('division of two matrices')
print(np.divide(a,b))

addition of two matrices
[[12 14]
 [25 15]]


subtraction of two matrices
[[-10 -10]
 [-19  -7]]


multiply of two matrices
[[11 24]
 [66 44]]


division of two matrices
[[0.09090909 0.16666667]
 [0.13636364 0.36363636]]


In [164]:
arr1 = np.array([3, 5, 6])

In [165]:
np.power(arr1, 3)

array([ 27, 125, 216], dtype=int32)

In [166]:
np.sqrt(arr1)

array([1.73205081, 2.23606798, 2.44948974])

In [169]:
arr2 = np.array([[1,2,3],[4,5,6],[7,8,9]])

In [174]:
arr2

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [176]:
np.percentile(arr2, 80, axis = 1)

array([2.6, 5.6, 8.6])

In [186]:
print(np.mean(arr2,axis=1))
print(np.median(arr2,axis=1))
print(np.std(arr2,axis=1))

[2. 5. 8.]
[2. 5. 8.]
[0.81649658 0.81649658 0.81649658]


In [187]:
print(np.mean(arr2,axis=0))
print(np.median(arr2,axis=0))
print(np.std(arr2,axis=0))

[4. 5. 6.]
[4. 5. 6.]
[2.44948974 2.44948974 2.44948974]


### Dataframes = it is nothing but a table
#### every single column in the dataframe is called series


## Pandas

In [199]:
import pandas as pd

In [205]:
a = np.array([10, 2, 50, 70])
s = pd.Series(a)

In [206]:
type(a)

numpy.ndarray

In [207]:
type(s)

pandas.core.series.Series

In [208]:
print(s)

0    10
1     2
2    50
3    70
dtype: int32


In [213]:
a = np.array([10, 2, 50, 70])
s = pd.Series(a, index = [10, 20, 30, 40])

In [214]:
print(s)

10    10
20     2
30    50
40    70
dtype: int32


In [252]:
a1 = {10: 'chennai', 20: 'hyderabad', 30: 'banglore'}
s2 = pd.Series(a1, index = [1, 2, 3])

In [253]:
print(s2)

1    NaN
2    NaN
3    NaN
dtype: object


In [241]:
type(a1)

numpy.ndarray

In [242]:
type(s2)

pandas.core.series.Series

In [258]:
a1 = {10: 'chennai', 20: 'hyderabad', 30: 'banglore'}
s2 = pd.Series(a1, index = [20, 30, 10])

In [261]:
print(s2)

20    hyderabad
30     banglore
10      chennai
dtype: object
hyderabad


In [267]:
a = np.array([10, 2, 50, 70])
len1 = len(a)
s = pd.Series(a, index = range(1, len1+1))

In [268]:
print(s)

1    10
2     2
3    50
4    70
dtype: int32


In [271]:
a1 = {10: 'chennai', 20: 'hyderabad', 30: 'banglore'}
s2 = pd.Series(a1, index = [20, 30, 10])

In [275]:
s1 = pd.Series(a1)
s1

10      chennai
20    hyderabad
30     banglore
dtype: object